### PR TITLE
13.0

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/help-c-cpp could you help me target the correct version of OSX.

It seems I'm hitting a missing symbol for `___darwin_check_fd_set_overflow`, which seems to have become available in Xcode 11.4???

**Comment by xhochy** [comment]
See https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by hmaarrfk** [comment]
Hmmm, I still don't understand what is going on

https://gitlab.isc.org/isc-projects/kea/-/issues/1259

**Comment by ocefpaf** [comment]
@hmaarrfk I'm closing this one b/c I just merged #84. Let me know if you need this particular version and we can work on it.

**Pull request closed without merging**
