### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by msarahan**
Builds on #1 - uses msys2 to build, and fixes tests on windows by running a postgres server for the tests to connect to.

Adds @gillins as a maintainer, due to his work on this recipe.

### CODE REVIEW

**Comment by msarahan** [comment]
Looking at the artifacts from https://ci.appveyor.com/project/conda-forge/postgresql-feedstock/build/job/5yj5i5segxoacdq1/artifacts, I'm inclined to think that we're getting appveyor's built-in postgres install coming into play here.

**Comment by ocefpaf** [comment]
Wow! Thanks for digging into that! I guess we can [remove it](https://www.appveyor.com/docs/services-databases#postgresql) in the `bld.bat`. Ugly, but it works...

Ideally we should removed it in the `appveyor.yaml`, but that won't hold after a re-rendering, and the removal is specific to this `feedstock` only to be added to `conda-smithy`.

**Comment by msarahan** [comment]
No dice.  Seems like this error might be the snag: https://ci.appveyor.com/project/conda-forge/postgresql-feedstock/build/1.0.10/job/1wdw5hrouuxkilni#L8705

**Comment by ocefpaf** [comment]
Are you in a point were patching the tests to skip that one is an option?

**Comment by msarahan** [comment]
We can try that.  I'm kind of thinking that this will bite us with all of the tests (and don't understand why so many tests are actually passing)

**Comment by msarahan** [comment]
By the way, this is only the first of several test batteries.  If we kill this one table thing from all the suites, maybe it will work?

**Comment by gillins** [comment]
Do you need to stop AppVeyor's `postgres` first? Deleting the folder may fail as the files are in use otherwise...

**Comment by msarahan** [comment]
I don't think it should be started.  Based on the link that @ocefpaf  posted, you have to start it by listing it as a service.  I'm up for any new ideas, though.  This is really troublesome.  I'm also not clear on how to best skip this test, should we choose to do so.

If you dig into this, note that lines with ERROR are not necessarily errors.  Basically, the output should match some pre-determined string, like https://github.com/postgres/postgres/blob/REL9_5_STABLE/src/test/regress/output/tablespace.source and the problem is that we are not matching that (as far as I can tell)

**Comment by gillins** [comment]
Would be good to know what the difference is. Can we copy the result from AppVeyor and inspect it? Would also be good to confirm the right `diff` is being called.

Weird that is works locally (ie not AppVeyor). Do we know if any of the `postgres` [environment variables](https://www.postgresql.org/docs/8.4/static/libpq-envars.html) are set on AppVeyor?

**Comment by msarahan** [comment]
The difference is being collected as an artifact now: https://ci.appveyor.com/project/conda-forge/postgresql-feedstock/build/1.0.14/job/y99g0anh184931w8/artifacts - I welcome your eyes.

> Weird that is works locally (ie not AppVeyor).

This is very weird.

> Do we know if any of the postgres environment variables are set on AppVeyor?

I will output all variables and see what shakes out.

**Comment by gillins** [comment]
Still permission errors. I wonder if the AppVeyor install is still being picked up somehow...

**Comment by msarahan** [comment]
I am calling it a night, Sam.  If you want to take over, feel free to fork and rebase as necessary.

**Comment by msarahan** [comment]
Relevant bug report: https://www.postgresql.org/message-id/CY1PR10MB086069CDD85200608782ABBF94040%40CY1PR10MB0860.namprd10.prod.outlook.com

Not sure what our answer should be.  Might be able to patch such that the tests add a user argument, but I don't know why this would be necessary on AppVeyor, but not locally.

**Comment by msarahan** [comment]
This is working locally for each compiler now.  Appveyor is hanging at the end of the build, though.

**Comment by msarahan** [comment]
@ocefpaf @gillins  - this appears to be green.  I think my eyes are not deceiving me - I ran out of beer yesterday.  Please review when you can.

**Comment by ocefpaf** [comment]
:tada: :tada: :tada: 

@msarahan amazing work! My limited Windows knowledge cannot start to comprehend all you did here. Thanks for the effort and sorry it took so much of your time.

Merging this as @gillins is out and maybe a field test is in order.

**Comment by gillins** [comment]
Yes well done @msarahan - very impressive!

**Pull request merged**
