### PR TITLE
build with readline support

### LINKED ISSUE #13: Please compile with readline support
I am thankful for the efforts made to provide postgresql for conda, but not having readline support make usage of `psql` not much fun :(  I assume there is a valid reason for not including it, so am curious about it.  Seems like readline is in conda already?

### PR DESCRIPTION
**Pull request by akrherz**
fixes #13

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
We probably want to link with the conda-forge readline on osx and linux

**Comment by akrherz** [comment]
@mariusvniekerk I boggled that, but noticed how `--with-openssl` doesn't seem to specify any conda-forge openssl PATH and was not sure how to do that for `--with-readline`.  I do need to update `meta.yaml` to include this readline requirement as well.

**Comment by mariusvniekerk** [comment]
So i blelieve that the 
```
--with-libraries=$PREFIX/lib \
 --with-includes=$PREFIX/include \
``` 
deals with it.  As long as we have readline in the $PREFIX which we can get by adding it into the meta file we should be okay.

**Comment by akrherz** [comment]
@mariusvniekerk Thank you very much, updated my PR.

**Comment by akrherz** [comment]
no readline on windows it appears, so I think this should be good to go.

**Comment by mariusvniekerk** [comment]
Can you build the build number?  Otherwise we dont get new packages.

**Comment by akrherz** [comment]
@mariusvniekerk done.

**Pull request merged**
