### PR TITLE
Add Windows build

### PR DESCRIPTION
**Pull request by ocefpaf**
@gillins, @msarahan, and @patricksnape any advice here on how to fix the Windows build of `postgresql`?

### CODE REVIEW

**Comment by patricksnape** [comment]
Only one test is failing, we need to have a look at that regression output file.

**Comment by gillins** [comment]
When I run the build locally, I get the message below. What is the best way to get `diff`? Is it always installed with `msys2`?

```
test tablespace               ... 'diff' is not recognized as an internal or ext
ernal command,
operable program or batch file.
diff command not found: diff -w "C:/Users/sam/Miniconda3/conda-bld/work/postgres
ql-9.5.3/src/test/regress/expected/tablespace.out" "C:/Users/sam/Miniconda3/cond
a-bld/work/postgresql-9.5.3/src/test/regress/results/tablespace.out" > "C:/Users
/sam/Miniconda3/conda-bld/work/postgresql-9.5.3/src/test/regress/results/tablesp
ace.out.diff"
```

**Comment by ocefpaf** [comment]
@gillins for the `krb5` I used the `msys2` that is pre-installed in AppVeyor by adding

`set PATH=%PATH%;C:\msys64\usr\bin`

at the top of the `bld.bat`.

@msarahan are there any news about `msys2` in the default channel?

**Comment by gillins** [comment]
> set PATH=%PATH%;C:\msys64\usr\bin

Might be worth a try. The `msys2` on my PC doesn't have `diff`, but the AppVeyor install hopefully might be more complete.

**Comment by gillins** [comment]
I can confirm that having `diff` in the `PATH` allows the tests to pass on my PC.

However, `installcheck` seems to have problems connecting to the database - which seems to make sense since one hasn't been set up. I'm not sure this is a valid test to run in this case.

**Comment by ocefpaf** [comment]
> I can confirm that having `diff` in the `PATH` allows the tests to pass on my PC.

I am testing adding the path `MSYS2` now. Let's see if AppVeyor has `diff`.

> However, `installcheck` seems to have problems connecting to the database - which seems to make sense since one hasn't been set up. I'm not sure this is a valid test to run in this case.

Yeah. That looks like a "known failure" kind of test to me.

**Comment by gillins** [comment]
Sigh, so still no go. Adding `where diff` to `bld.bat` might help us debug what is or isn't being called. You may have to add `pacman -S diffutils` to get mysy2's `diff` - I'm not sure.

Out of interest - why are we building the whole database rather than just the client libs? Setting up database servers seems a bit outside the scope for `conda` or am I wrong? We would really have to be onto it with security.

**Comment by ocefpaf** [comment]
> Sigh, so still no go. Adding `where diff` to `bld.bat` might help us debug what is or isn't being called. You may have to add `pacman -S diffutils` to get mysy2's `diff` - I'm not sure.

I will try that.

> Out of interest - why are we building the whole database rather than just the client libs?

No idea to be honest. I was just trying to get this recipe out of `staged-recipes`.

> Setting up database servers seems a bit outside the scope for `conda` or am I wrong? We would really have to be onto it with security.

Make senses. @msarahan what say you?

**Comment by gillins** [comment]
Same problem... I don't understand why it works on my VM. Can we extract `tabelspace.out` from AppVeyor?

**Comment by ocefpaf** [comment]
> Same problem... I don't understand why it works on my VM. Can we extract tabelspace.out from AppVeyor?

I believe so but I never tried. Time to go :sleeping: here. I will take another look tomorrow.

**Comment by msarahan** [comment]
I have this working locally - just polishing.  Will push a PR very soon.

**Comment by msarahan** [comment]
On the topic of providing full database vs. just library: I'd like to provide both.  One reason is that I don't want to rewrite their build scripts.  It's possible that we need only select a project within the overall solution.  I just don't want to dig into it.  I also think that providing the database as a conda package may be useful to someone.  If I could ```conda install``` a complete web framework, database and all, I think that would be useful.

**Comment by ocefpaf** [comment]
> I have this working locally - just polishing. Will push a PR very soon.

Closing this as I spent all my Windows knowledge here :smile: 

Thanks @msarahan!

**Pull request closed without merging**
