### PR TITLE
Adding SPDX license identifier to `postgresql` output

### PR DESCRIPTION
**Pull request by fhoehle**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
This PR was green from yesterday and given what I appear to think is a transient failure in PR #181, please pardon my power cycle of this PR to see if it is still green now.

@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
I rebased this

@conda-forge-admin please rerender

**Comment by fhoehle** [comment]
thanks @akrherz @hmaarrfk

**Pull request merged**
