### PR TITLE
Add tzdata as dependency

### PR DESCRIPTION
**Pull request by xylar**
`tzcode` has incorrectly been shipping the contents of `shared/zoneinfo` and clobbering the same contents from `tzdata`.  These packages appear to need both, and will be broken as soon as `tzcode` is fixed.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
See https://github.com/conda-forge/tzcode-feedstock/pull/12 for more discussion.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
Thank you for fixing this! I've been meaning to tackle the tzcode/tzdata for a while now...

**Pull request merged**
