### PR TITLE
Add dual builds of libxml2

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
this is ready for review

**Review by akrherz — APPROVED** [review]
I trust @hmaarrfk's judgement over what I did in #196, but looking at the build log on libxml2 2.11 + linux64, I see this:
```
"libpq-16.1-h33b98f1_7.conda": {
    "recipe": {
      "c_compiler": "gcc",
      "c_compiler_version": "12",
      "channel_targets": "conda-forge main",
      "krb5": "1.21",
      "openssl": "3",
      "target_platform": "linux-64"
    }
```
So it appears the libxml2 dependency is getting dropped here for libpq?

**Comment by akrherz** [comment]
Oh, I also am of the opinion that `libpq` needs a run section added.  I believe the lack of a run section resulted in the bad libpq build in #193

**Comment by hmaarrfk** [comment]
> Oh, I also am of the opinion that libpq needs a run section added. I believe the lack of a run section resulted in the bad libpq build in https://github.com/conda-forge/postgresql-feedstock/pull/193

The thing is that all the packages i removed have a line like `run_exports`

that will ensure that the correct runtime dependency is added:
https://github.com/conda-forge/openssl-feedstock/blob/main/recipe/meta.yaml#L36

So i think it is enough.

**Comment by hmaarrfk** [comment]
> So it appears the libxml2 dependency is getting dropped here for libpq?

this is the list of dependencies that is used to generate the hash.


linux + libxml2 2.11

```
2023-12-08T23:43:00.8426138Z   "libpq-16.1-h33b98f1_7.conda": {
2023-12-08T23:43:00.8426666Z     "recipe": {
2023-12-08T23:43:00.8427091Z       "c_compiler": "gcc",
2023-12-08T23:43:00.8427519Z       "c_compiler_version": "12",
2023-12-08T23:43:00.8428009Z       "channel_targets": "conda-forge main",
2023-12-08T23:43:00.8428911Z       "krb5": "1.21",
2023-12-08T23:43:00.8429304Z       "openssl": "3",
2023-12-08T23:43:00.8429715Z       "target_platform": "linux-64"
2023-12-08T23:43:00.8430115Z     }
2023-12-08T23:43:00.8430475Z   },
```

linux64 + libxml2 + 2.12
```
2023-12-08T23:43:13.4421102Z   "libpq-16.1-h33b98f1_7.conda": {
2023-12-08T23:43:14.4385618Z     "recipe": {
2023-12-08T23:43:14.4394470Z       "c_compiler": "gcc",
2023-12-08T23:43:14.4395243Z       "c_compiler_version": "12",
2023-12-08T23:43:14.4396228Z       "channel_targets": "conda-forge main",
2023-12-08T23:43:14.4396990Z       "krb5": "1.21",
2023-12-08T23:43:14.4397419Z       "openssl": "3",
2023-12-08T23:43:14.4398127Z       "target_platform": "linux-64"
2023-12-08T23:43:14.4398504Z     }
2023-12-08T23:43:14.4398836Z   },
```

so as you can see, the hash is the exact same. I don't think this is such a problem since libpq doesn't depend on any subpackage. if it did, then I would be worried. In effect, we are building 2 x `libpq` but only one of these will get uploaded. I think it is fine for this specific usecase.

**Pull request merged**
