### PR TITLE
Platforms build options synchronisation

### PR DESCRIPTION
**Pull request by flaviomartins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by flaviomartins** [comment]
@conda-forge-admin, please rerender

**Comment by flaviomartins** [comment]
@conda-forge-admin, please rerender

**Comment by flaviomartins** [comment]
Everything seems to have been picked up except LZ4 on windows. The lz4-c-feedstock does seem to provide the necessary liblz4.dll but meson cannot find it. Any ideas?

**Review by akrherz — APPROVED** [review]
This all seems excellent to me, thank you!

**Pull request merged**
