### PR TITLE
Bump version to postgres 9.6.1

### PR DESCRIPTION
**Pull request by postelrich**

### CODE REVIEW

**Comment by postelrich** [comment]
@jakirkham What needs to be done to get appveyor passing?

**Comment by jakirkham** [comment]
So I don't maintain this feedstock @postelrich . Thus I'm not the best person to ask about how to get this package to build.

That being said, some of the issues encountered here like the download issues with Miniconda on Travis CI and the path issues on AppVeyor, are due to this feedstock not being re-rendered in a long time.

Normally [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) is a straightforward process. However, this feedstock makes use of some things that cause re-rendering to fail. I've put together some changes for `conda-smithy` that *should* fix this and am testing them out on this feedstock.

xref: https://github.com/conda-forge/conda-smithy/pull/401
xref: https://github.com/conda-forge/postgresql-feedstock/pull/6

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/postgresql-feedstock/pull/7 ) for the re-rendering.

**Comment by ocefpaf** [comment]
Closing this in favor of #10

**Pull request closed without merging**
